const politics = {
    accelerometer: [],
    'ambient-light-sensor': [],
    autoplay: [],
    camera: [],
    'display-capture': [],
    'document-domain': [],
    'document-write': [],
    'encrypted-media': [],
    'execution-while-not-rendered': [],
    'execution-while-out-of-viewport': [],
    'font-display-late-swap': [],
    fullscreen: [],
    geolocation: [],
    gyroscope: [],
    'interest-cohort': [],
    'layout-animations': [],
    'legacy-image-formats': [],
    'loading-frame-default-eager': [],
    magnetometer: [],
    microphone: [],
    midi: [],
    'navigation-override': [],
    notifications: [],
    'oversized-images': [],
    payment: [],
    'picture-in-picture': [],
    'publickey-credentials': [],
    push: [],
    serial: [],
    speaker: [],
    'sync-script': [],
    'sync-xhr': [],
    'unoptimized-images': [],
    'unoptimized-lossless-images':[],
    'unoptimized-lossy-images': [],
    'unsized-media': [],
    usb: [],
    'vertical-scroll': [],
    vibrate: [],
    vr: [],
    'wake-lock': [],
    xr: [],
    'xr-spatial-tracking': []
  }

export default politics;